apiVersion: apps/v1
kind: Deployment
metadata:
  name: rahla
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rahla
    spec:
      containers:
      - name: rahla
        volumeMounts:
        - name: settings-xml-volume
          subPath: "settings.xml"
          mountPath: "/rahla/etc/settings.xml"
          readOnly: true

      volumes:
      - name: settings-xml-volume
        configMap:
          name: settings-xml-cm

