startDelaySecs: 5
ssl: false
includeObjectNames:
  - org.apache.camel:type=routes,*
  - org.apache.camel:type=processors,*
  - org.apache.camel.metrics:*
  - com.zaxxer.hikari:*
rules:
  # Route level
  - pattern: 'org.apache.camel<context=.+-([^,]+), type=routes, name=\"([^,]+)\"><>ExchangesCompleted'
    name: camel_route_exchanges_completed_total
    help: Exchanges Completed
    type: COUNTER
    labels:
      context: $1
      route: $2
  - pattern: 'org.apache.camel<context=.+-([^,]+), type=routes, name=\"([^,]+)\"><>ExchangesFailed'
    name: camel_route_exchanges_failed_total
    help: Exchanges Failed
    type: COUNTER
    labels:
      context: $1
      route: $2
  - pattern: 'org.apache.camel<context=.+-([^,]+), type=routes, name=\"([^,]+)\"><>ExchangesInflight'
    name: camel_route_exchanges_inflight_total
    help: Exchanges Inflight
    type: GAUGE
    labels:
      context: $1
      route: $2
  - pattern: 'org.apache.camel<context=.+-([^,]+), type=routes, name=\"([^,]+)\"><>ExchangesTotal'
    name: camel_route_exchanges_total
    help: Exchanges Total
    type: COUNTER
    labels:
      context: $1
      route: $2
  - pattern: 'org.apache.camel<context=.+-([^,]+), type=routes, name=\"([^,]+)\"><>FailuresHandled'
    name: camel_route_failures_handled_total
    help: Failures Handled
    labels:
      context: $1
      route: $2
    type: COUNTER
  - pattern: 'org.apache.camel<context=.+-([^,]+), type=routes, name=\"([^,]+)\"><>ExternalRedeliveries'
    name: camel_route_external_redeliveries_total
    help: External Redeliveries
    labels:
      context: $1
      route: $2
    type: COUNTER
  - pattern: 'org.apache.camel<context=.+-([^,]+), type=routes, name=\"([^,]+)\"><>MaxProcessingTime'
    name: camel_route_max_processing_time
    help: Maximum Processing Time
    labels:
      context: $1
      route: $2
    type: GAUGE
  - pattern: 'org.apache.camel<context=.+-([^,]+), type=routes, name=\"([^,]+)\"><>MeanProcessingTime'
    name: camel_route_mean_processing_time
    help: Mean Processing Time
    labels:
      context: $1
      route: $2
    type: GAUGE
  - pattern: 'org.apache.camel<context=.+-([^,]+), type=routes, name=\"([^,]+)\"><>MinProcessingTime'
    name: camel_route_min_processing_time
    help: Minimum Processing Time
    labels:
      context: $1
      route: $2
    type: GAUGE
  - pattern: 'org.apache.camel<context=.+-([^,]+), type=routes, name=\"([^,]+)\"><>LastProcessingTime'
    name: camel_route_last_processing_time
    help: Last Processing Time
    labels:
      context: $1
      route: $2
    type: GAUGE
  - pattern: 'org.apache.camel<context=.+-([^,]+), type=routes, name=\"([^,]+)\"><>DeltaProcessingTime'
    name: camel_route_delta_processing_time
    help: Delta Processing Time
    labels:
      context: $1
      route: $2
    type: GAUGE
  - pattern: 'org.apache.camel<context=.+-([^,]+), type=routes, name=\"([^,]+)\"><>Redeliveries'
    name: camel_route_external_redeliveries_total
    help: Redeliveries
    labels:
      context: $1
      route: $2
    type: COUNTER
  - pattern: 'org.apache.camel<context=.+-([^,]+), type=routes, name=\"([^,]+)\"><>TotalProcessingTime'
    name: camel_route_total_processing_time_total
    help: Total Processing Time
    labels:
      context: $1
      route: $2
    type: GAUGE

  - pattern: 'org.apache.camel<context=.+-([^,]+), type=routes, name=\"([^,]+)\"><>InflightExchanges'
    name: camel_route_exchanges_inflight_total
    help: Inflight Exchanges
    labels:
      context: $1
      route: $2
    type: GAUGE


  - pattern: 'org.apache.camel<context=.+-([^,]+), type=routes, name=\"([^,]+)\"><>UptimeMillis'
    name: camel_route_up
    help: Route uptime
    labels:
      context: $1
      route: $2
    type: GAUGE


  - pattern: 'org.apache.camel<context=.+-([^,]+), type=routes, name=\"([^,]+)\"><>LastExchangeCompletedTimestamp'
    name: camel_route_last_exchange_completed_timestamp
    help: Route uptime
    labels:
      context: $1
      route: $2
    type: GAUGE

  - pattern: 'org.apache.camel.metrics<type=counters, name=\"([^,]+)\"><>Count'
    name: $1
    help: Camel Metrics Counter, modify javaagent's config.yaml to improve the metric
    labels:
      context: $1
    type: GAUGE

  - pattern: 'com.zaxxer.hikari<type=Pool \(([^,]+)\)><>ActiveConnections'
    name: hikari_cp_active_connections
    help: Hikari CP ActiveConnections
    labels:
      pool: $1
    type: GAUGE

  - pattern: 'com.zaxxer.hikari<type=Pool \(([^,]+)\)><>ThreadsAwaitingConnection'
    name: hikari_cp_threads_awaitng_connection
    help: Hikari CP ThreadsAwaitingConnection
    labels:
      pool: $1
    type: GAUGE

  - pattern: 'com.zaxxer.hikari<type=Pool \(([^,]+)\)><>TotalConnections'
    name: hikari_cp_total_connections
    help: Hikari CP TotalConnections
    labels:
      pool: $1
    type: GAUGE

  - pattern: 'com.zaxxer.hikari<type=Pool \(([^,]+)\)><>IdleConnections'
    name: hikari_cp_idle_connections
    help: Hikari CP IdleConnections
    labels:
      pool: $1
    type: GAUGE



  # Processor level
  #  - pattern: 'org.apache.camel<context=.+-([^,]+), type=processors, name=\"([^,]+)\"><>ExchangesCompleted'
  #    name: org.apache.camel.ExchangesCompleted
  #    help: Exchanges Completed
  #    type: COUNTER
  #    labels:
  #      context: $1
  #      processor: $2
  #      type: processors
  #  - pattern: 'org.apache.camel<context=.+-([^,]+), type=processors, name=\"([^,]+)\"><>ExchangesFailed'
  #    name: org.apache.camel.ExchangesFailed
  #    help: Exchanges Failed
  #    type: COUNTER
  #    labels:
  #      context: $1
  #      processor: $2
  #      type: processors
  #  - pattern: 'org.apache.camel<context=.+-([^,]+), type=processors, name=\"([^,]+)\"><>ExchangesInflight'
  #    name: org.apache.camel.ExchangesInflight
  #    help: Exchanges Inflight
  #    type: GAUGE
  #    labels:
  #      context: $1
  #      processor: $2
  #      type: processors
  #  - pattern: 'org.apache.camel<context=.+-([^,]+), type=processors, name=\"([^,]+)\"><>ExchangesTotal'
  #    name: org.apache.camel.ExchangesTotal
  #    help: Exchanges Total
  #    type: COUNTER
  #    labels:
  #      context: $1
  #      processor: $2
  #      type: processors
  #  - pattern: 'org.apache.camel<context=.+-([^,]+), type=processors, name=\"([^,]+)\"><>FailuresHandled'
  #    name: org.apache.camel.FailuresHandled
  #    help: Failures Handled
  #    labels:
  #      context: $1
  #      processor: $2
  #      type: processors
  #    type: COUNTER
  #  - pattern: 'org.apache.camel<context=.+-([^,]+), type=processors, name=\"([^,]+)\"><>ExternalRedeliveries'
  #    name: org.apache.camel.ExternalRedeliveries
  #    help: External Redeliveries
  #    labels:
  #      context: $1
  #      processor: $2
  #      type: processors
  #    type: COUNTER
  #  - pattern: 'org.apache.camel<context=.+-([^,]+), type=processors, name=\"([^,]+)\"><>MaxProcessingTime'
  #    name: org.apache.camel.MaxProcessingTime
  #    help: Maximum Processing Time
  #    labels:
  #      context: $1
  #      processor: $2
  #      type: processors
  #    type: GAUGE
  #  - pattern: 'org.apache.camel<context=.+-([^,]+), type=processors, name=\"([^,]+)\"><>MeanProcessingTime'
  #    name: org.apache.camel.MeanProcessingTime
  #    help: Mean Processing Time
  #    labels:
  #      context: $1
  #      processor: $2
  #      type: processors
  #    type: GAUGE
  #  - pattern: 'org.apache.camel<context=.+-([^,]+), type=processors, name=\"([^,]+)\"><>MinProcessingTime'
  #    name: org.apache.camel.MinProcessingTime
  #    help: Minimum Processing Time
  #    labels:
  #      context: $1
  #      processor: $2
  #      type: processors
  #    type: GAUGE
  #  - pattern: 'org.apache.camel<context=.+-([^,]+), type=processors, name=\"([^,]+)\"><>LastProcessingTime'
  #    name: org.apache.camel.LastProcessingTime
  #    help: Last Processing Time
  #    labels:
  #      context: $1
  #      processor: $2
  #      type: processors
  #    type: GAUGE
  #  - pattern: 'org.apache.camel<context=.+-([^,]+), type=processors, name=\"([^,]+)\"><>DeltaProcessingTime'
  #    name: org.apache.camel.DeltaProcessingTime
  #    help: Delta Processing Time
  #    labels:
  #      context: $1
  #      processor: $2
  #      type: processors
  #    type: GAUGE
  #  - pattern: 'org.apache.camel<context=.+-([^,]+), type=processors, name=\"([^,]+)\"><>Redeliveries'
  #    name: org.apache.camel.Redeliveries
  #    help: Redeliveries
  #    labels:
  #      context: $1
  #      processor: $2
  #      type: processors
  #    type: COUNTER
  #  - pattern: 'org.apache.camel<context=.+-([^,]+), type=processors, name=\"([^,]+)\"><>TotalProcessingTime'
  #    name: org.apache.camel.TotalProcessingTime
  #    help: Total Processing Time
  #    labels:
  #      context: $1
  #      processor: $2
  #      type: processors
  #    type: GAUGE
  #  - pattern: 'org.apache.camel<context=.+-([^,]+), type=processors, name=\"([^,]+)\"><>InflightExchanges'
  #    name: org.apache.camel.InflightExchanges
  #    help: Inflight Exchanges
  #    labels:
  #      context: $1
  #      processor: $2
  #      type: processors
  #    type: COUNTER

  # Consumers
  #  - pattern: 'org.apache.camel<context=.+-([^,]+), type=consumers, name=\"([^,]+)\"><>InflightExchanges'
  #    name: org.apache.camel.InflightExchanges
  #    help: Inflight Exchanges
  #    labels:
  #      context: $1
  #      consumer: $2
  #      type: consumers
  #    type: GAUGE

  # Services