apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rahla.yaml
configMapGenerator:
  - name: rahla-env
  - name: deploy-cm
  - name: data-cm

images:
  - name: datatactics/rahla
    newTag: "latest"

generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  application: rahla