
resources:
- deployment.yaml
- service.yaml

configMapGenerator:
- name: rahla-base-env

- name: configs-cm
  files:
  - org.ops4j.pax.logging.cfg
  - rahla.metrics.cfg

- name: deploy-cm
- name: data-cm

images:
  - name: dttctcs/rahla
    newTag: "latest"

generatorOptions:
  disableNameSuffixHash: true