---
apiVersion: v1
kind: Service
metadata:
  name: rahla
  labels:
    app: rahla
spec:
  ports:
  - name: osgi
    port: 8181
    protocol: TCP
    targetPort: osgi
  selector:
    app: rahla
  type: ClusterIP 
  
---
apiVersion: v1
kind: Service
metadata:
  name: rahla-ssh
  labels:
    app: rahla
spec:
  ports:
  - name: ssh
    port: 8181
    protocol: TCP
    targetPort: ssh
  selector:
    app: rahla
  type: ClusterIP 
   


