
namespace: my-namespace

commonLabels:
  customer: myCustomer
  application: myAppication
  service: rahla
  serviceType: integration

configMapGenerator:
- name: deploy-cm
  behavior: merge
  files:
  - config.cfg

- name: env-cm
  envs:
  - environment.properties

- name: deploy-cm
  behavior: merge
  files:
  - features.xml

- name: data-cm
  behavior: replace
  files:
  - keystore.jks

- name: deploy-cm
  behavior: merge
  files:
  - context1.xml
  - context2.xml

generatorOptions:
  disableNameSuffixHash: false

patchesStrategicMerge:
- patch.yaml
- settings-xml-patch.yaml

resources:
- ../base