
resources:
- deployment.yaml
- service.yaml

configMapGenerator:
- name: rahla-base-env

- name: configs-cm
  files:
  - configs/org.ops4j.pax.logging.cfg
  - configs/rahla.metrics.cfg

- name: deploy-cm
- name: data-cm

images:
  - name: dttctcs/rahla
    newTag: "4.0.2"

generatorOptions:
  disableNameSuffixHash: true