---
apiVersion: v1
kind: Service
metadata:
  name: rahla
  labels:
    app: rahla
spec:
  ports:
  - name: osgi
    port: 8181
    protocol: TCP
    targetPort: osgi
  selector:
    app: rahla
  type: ClusterIP  

